name: (Push) Github Action Judge

on:
  push:
    branches: ["**"]

jobs:
  set-up-judge:
    name: Set-up Judge
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3

      - id: setmatrix
        name: Configure judge
        run: |
          USERS=$(find .judge/users -name '*.yaml')
          echo "$USERS" |
              jq --slurp --raw-input 'split("\n")[:-1]' |
              jq "{\"filepath\": .[] }" |
              jq -sc "{ \"include\": . }" >users
          cat ./users

          matrixStringifiedObject=$(cat ./users)
          echo "::set-output name=matrix::$matrixStringifiedObject"

      - name: Create an empty submission
        run: touch submission.yaml

      - name: Upload submission
        uses: actions/upload-artifact@v3
        with:
          name: submission
          path: submission.yaml

  submit-judge:
    name: Submit to Judge
    needs: set-up-judge
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.set-up-judge.outputs.matrix)}}

    outputs:
      max-parallel: 1
      matrix: ${{ steps.submitjudge.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3

      - name: Install yq
        uses: mikefarah/yq@v4.27.2

      - name: Set up judge config via ${{ matrix.filepath }}
        run: |
          json=`cat ${{ matrix.filepath }} | yq e -o=json`
          echo "SUBMIT_JSON=`echo $(jq -r '.submits' <<< "$json")`" >> $GITHUB_ENV
          echo "USER=`echo $(jq -r '.user' <<< "$json")`" >> $GITHUB_ENV

      - name: Display submission info
        run: |
          echo 'USER: ${{ env.USER }}'
          echo 'SUBMIT_JSON: ${{ env.SUBMIT_JSON }}'

      - name: Submit to judge
        id: submitjudge
        run: |
          readarray -t SUBMITS < <(jq -c '.[]' <<<'${{ env.SUBMIT_JSON }}')

          for submit in "${SUBMITS[@]}"; do
            PROBLEM=$(jq '.problem' <<<"$submit")
            CODE=$(jq '.code' <<<"$submit")
            echo $PROBLEM
            echo $CODE
          done

          MATRIX=$(jq -c "{ \"include\": . }" <<<$SUBMIT_JSON)
          echo "::set-output name=matrix::$MATRIX"

      - name: Fetch submission
        uses: actions/download-artifact@v3
        with:
          name: submission

      - shell: bash
        run: |
          value=`cat submission.yaml`
          echo hello >> submission.yaml

      - name: Update submission
        uses: actions/upload-artifact@v3
        with:
          name: submission
          path: submission.yaml

  run-judge:
    name: Run Judge
    needs: submit-judge
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.submit-judge.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
