name: C Judge

on:
  push:
    branches: [ "main", "feature/judge" ]
  pull_request:
    branches: [ "main", "feature/judge" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: judge 
      run: 
      - cd ./lucetre/
      - sh ./judge.sh
