name: (Push) Github Action Judge

on:
  push:
    branches: ["**"]

jobs:
  set-up-judge:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3

      - id: setmatrix
        name: Configure judge
        run: |
          matrixArray=$(find .judge/user -name '*.json')
          echo "$matrixArray" | \
          jq --slurp --raw-input 'split("\n")[:-1]' | \
          jq  "{\"filepath\": .[] }" | \
          jq -sc "{ \"include\": . }" > tmp
          cat ./tmp
          matrixStringifiedObject=$(cat ./tmp)
          echo "::set-output name=matrix::$matrixStringifiedObject"

  submit-judge:
    needs: set-up-judge
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.set-up-judge.outputs.matrix)}}

    outputs:
      matrix: ${{ steps.submitjudge.outputs.matrix }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up judge config via ${{ matrix.filepath }}
        run: |
          json=`cat ${{ matrix.filepath }}`
          echo "SUBMIT_JSON=`echo $(jq -r '.submits' <<< "$json")`" >> $GITHUB_ENV
          echo "USER=`echo $(jq -r '.user' <<< "$json")`" >> $GITHUB_ENV

      - name: Display submission info
        run: |
          echo 'USER: ${{ env.USER }}'
          echo 'SUBMIT_JSON: ${{ env.SUBMIT_JSON }}'

      - name: Submit to judge
        id: submitjudge
        run: |
          readarray -t SUBMITS < <(jq -c '.[]' <<<'${{ env.SUBMIT_JSON }}')

          for submit in "${SUBMITS[@]}"; do
            PROBLEM=$(jq '.problem' <<<"$submit")
            CODE=$(jq '.code' <<<"$submit")
            echo $PROBLEM
            echo $CODE
          done

          MATRIX=$(jq -sc "{ \"include\": . }" <<<$SUBMIT_JSON)
          echo "::set-output name=matrix::$MATRIX"

  run-judge:
    needs: submit-judge
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{fromJson(needs.submit-judge.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
