name: PR - Github Action Judge

on:
  pull_request:
    branches: ["main"]
jobs:
  judge:
    strategy:
      fail-fast: false
      matrix:
        set:
          - problem: 10127
            code: "nick11967/Ch 5/36 Ones/ones.cpp"
          - problem: 10157
            code: "nick11967/Ch 6/44 Expressions/expressions2.cpp"
          - problem: 846
            code: "nick11967/Ch 6/48 Steps/steps.cpp"


    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Initialize Judge Result
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            [![PR - Github Action Judge](https://github.com/22S-LGN-PS/programming-challenges/actions/workflows/judge-on-pull-request.yaml/badge.svg)](https://github.com/22S-LGN-PS/programming-challenges/actions/workflows/judge-on-pull-request.yaml)
            |Problem|Source Code|Status|
            |:------:|:---:|:---:|
            |**${{ matrix.set.problem }}**|${{ matrix.set.code }}|:question:|
          comment_includes: ${{ matrix.set.code }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Action Judge
        run: sh .judge/submit.sh "${{ matrix.set.problem }}" "${{ matrix.set.code }}"

      - name: Comment Judge Result
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            [![PR - Github Action Judge](https://github.com/22S-LGN-PS/programming-challenges/actions/workflows/judge-on-pull-request.yaml/badge.svg)](https://github.com/22S-LGN-PS/programming-challenges/actions/workflows/judge-on-pull-request.yaml)
            |Problem|Source Code|Status|
            |:------:|:---:|:---:|
            |**${{ matrix.set.problem }}**|${{ matrix.set.code }}|:+1:|
          reactions: hooray
          comment_includes: ${{ matrix.set.code }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
