name: Github Action Judge

on:
  # push:
  #   branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  judge:
    strategy:
      fail-fast: false
      matrix:
        set:
          - problem: 100
            code: "lucetre/chap01/100/main.cpp"
          - problem: 10038
            code: "lucetre/chap02/10038/main.cpp"
          - problem: 10010
            code: "lucetre/chap03/10010/main.cpp"
          # - problem: 100
          #   code: "nick11967/Ch 1/1 The 3n+1 Problem/the_3n+1_problem.cpp"
          # - problem: 10038
          #   code: "nick11967/Ch 2/9 Jolly Jumper/jolly_jumper.cpp"
          # - problem: 100
          #   code: "gracekim027/3n+1/src/test.java"
          # - problem: 10038
          #   code: "gracekim027/JollyJumper/src/test.java"

    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3
      - name: Github Action Judge
        run: sh .judge/submit.sh "${{ matrix.set.problem }}" "${{ matrix.set.code }}"

      - name: Comment Judge Result
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ${{ matrix.set.problem }}
            ${{ matrix.set.code }}
          reactions: hooray
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
