name: Github Action Judge

on:
  # push:
  #   branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  judge:
    strategy:
      fail-fast: false
      matrix:
        set:
          #- problem: 100
          #  code: "nick11967/Ch 1/1 The 3n+1 Problem/the_3n+1_problem.cpp"
          #- problem: 10038
          #  code: "nick11967/Ch 2/9 Jolly Jumper/jolly_jumper.cpp"
          #- problem: 10149
          #  code: "nick11967/Ch 2/16 Yahtzee/yahtzee.cpp"
          #- problem: 10010
          #  code: "nick11967/Ch 3/18 Wheres Waldorf/waldorf.cpp"
          #- problem: 10252
          #  code: "nick11967/Ch 3/19 Common Permutation/common_permutation.cpp"
          - problem: 10026
            code: "nick11967/Ch 4/29 Shoemakers Problem/shoemakers_problem.cpp"
          - problem: 10152
            code: "nick11967/Ch 4/31 ShellSort/shellsort.cpp"

    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Initialize Judge Result
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            |Problem|Source Code|Status|
            |:------:|:---:|:---:|
            |**${{ matrix.set.problem }}**|${{ matrix.set.code }}|:question:|
          comment_includes: ${{ matrix.set.code }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Action Judge
        run: sh .judge/submit.sh "${{ matrix.set.problem }}" "${{ matrix.set.code }}"

      - name: Comment Judge Result
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            |Problem|Source Code|Status|
            |:------:|:---:|:---:|
            |**${{ matrix.set.problem }}**|${{ matrix.set.code }}|:+1:|
          reactions: hooray
          comment_includes: ${{ matrix.set.code }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
