name: (Push) Github Action Judge

on:
  push:
    branches: ["**"]

jobs:
  judge:
    strategy:
      fail-fast: false
      matrix:
        set:
          - problem: 10018
            code: "nick11967/Ch 5/10018 Reverse and Add/reverseandadd.cpp"
          - problem: 10026
            code: "nick11967/Ch 4/29 Shoemakers Problem/shoemakers_problem.cpp"

    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Github Action Judge
        run: sh .judge/submit.sh "${{ matrix.set.problem }}" "${{ matrix.set.code }}"
