name: (Push) Github Action Judge

on:
  push:
    branches: ["**"]

jobs:
  judge:
    strategy:
      fail-fast: false
      matrix:
        set:
          - problem: 100
            code: "nick11967/Ch 1/1 The 3n+1 Problem/the_3n+1_problem.cpp"
          - problem: 10038
            code: "nick11967/Ch 2/9 Jolly Jumper/jolly_jumper.cpp"
          - problem: 10010
            code: "nick11967/Ch 3/18 Wheres Waldorf/waldorf.cpp"
          - problem: 10252
            code: "nick11967/Ch 3/19 Common Permutation/common_permutation.cpp"
          - problem: 10018
            code: "nick11967/Ch 5/10018 Reverse and Add/reverseandadd.cpp"

    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Github Action Judge
        run: sh .judge/submit.sh "${{ matrix.set.problem }}" "${{ matrix.set.code }}"
