name: (Push) Github Action Judge

on:
  push:
    branches: ["**"]

jobs:
  set-job-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: setmatrix
        name: Configure judge
        run: |
          matrixArray=$(find .judge/user -name '*.json')
          echo "$matrixArray" | \
          jq --slurp --raw-input 'split("\n")[:-1]' | \
          jq  "{\"filepath\": .[] }" | \
          jq -sc "{ \"include\": . }" > tmp
          cat ./tmp
          matrixStringifiedObject=$(cat ./tmp)
          echo "::set-output name=matrix::$matrixStringifiedObject"

  run:
    needs: set-job-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.set-job-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - name: Github Action Judge ${{ matrix.filepath }}
        run: |
          json=`cat ${{ matrix.filepath }}`
          echo $json
          user=`echo $(jq -r '.user' <<< "$json")`
      # - run: |
      #     echo '${{ fromJson(env.USER_JSON).user }}'
