name: (Push) gracekim027

on:
  push:
    branches: ["gracekim027"]

jobs:
  judge:
    strategy:
      fail-fast: false
      matrix:
        set:
          - problem: 100
            code: "gracekim027/3n+1/src/test.java"

    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Github Action Judge
        run: sh .judge/submit.sh "${{ matrix.set.problem }}" "${{ matrix.set.code }}"
