name: (Push) Github Action Judge

on:
  push:
    branches: ["**"]

jobs:
  judge:
    strategy:
      fail-fast: false
      matrix:
        set:
          - problem: 10127
            code: "nick11967\Ch 5\36 Ones\ones.cpp"
          - problem: 10157
            code: "nick11967\Ch 6\44 Expressions\expressions.cpp"
          - problem: 846
            code: "nick11967\Ch 6\48 Steps\steps.cpp"

    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3

      - name: Github Action Judge
        run: sh .judge/submit.sh "${{ matrix.set.problem }}" "${{ matrix.set.code }}"
