name: build

on:
  push:
    branches: ["**"]

jobs:
  set-job-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - id: setmatrix
        run: |
          matrixArray=$(find .judge/user -name '*.json')
          echo "$matrixArray" | \
          jq --slurp --raw-input 'split("\n")[:-1]' | \
          jq  "{\"filepath\": .[] }" | \
          jq -sc "{ \"include\": . }" > tmp
          cat ./tmp
          matrixStringifiedObject=$(cat ./tmp)
          echo "::set-output name=matrix::$matrixStringifiedObject"

  run-job-matrix:
    needs: set-job-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.set-job-matrix.outputs.matrix)}}
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - run: echo ${{ matrix.filepath }}
